galaxy_info:
  author: Vítězslav Dvořák <info@vitexsoftware.cz>
  description: Role for managing MultiFlexi
  company: Vitex Software

  issue_tracker_url: https://github.com/VitexSoftware/multiflexi-ansible-collection/issues

  license: MIT

  min_ansible_version: '2.1'

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  platforms:
    - name: Debian
      versions:
        - '10'
        - '11'
        - '12'
    - name: Ubuntu
      versions:
        - '20.04'
        - '22.04'
        - '24.04'

  galaxy_tags: []
    # List tags for your role here, one per line. A tag is a keyword that describes
    # and categorizes the role. Users find roles by searching for tags. Be sure to
    # remove the '[]' above, if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
    #       Maximum 20 tags per role.

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
