galaxy_info:
  author: Vítězslav Dvořák <info@vitexsoftware.cz>
  description: Install the OpenTelemetry logging engine (Grafana Loki) for MultiFlexi OTEL logs/data
  company: Vitex Software

  issue_tracker_url: https://github.com/VitexSoftware/multiflexi-ansible-collection/issues

  license: MIT

  min_ansible_version: '2.1'

  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - opentelemetry
    - otel
    - logging
    - loki
    - observability
    - multiflexi

dependencies: []
