---
- name: Install MultiFlexi multi package
  ansible.builtin.apt:
    name: 'abraflexi-webhook-acceptor-{{ db_type | default("sqlite") }}'
    state: present
  when: db_type in multiflexi_server_database_engines
  tags: ['multiflexi']

- name: Enable abraflexi-webhook-acceptor
  ansible.builtin.command:
    cmd: a2enconf abraflexi-webhook-acceptor
    creates: /etc/apache2/conf-enabled/abraflexi-webhook-acceptor.conf
  notify:
    - Restart apache2
