---
# tasks file for multiflexi_server
- name: Install MultiFlexi multi package
  ansible.builtin.apt:
    name: 'multiflexi-{{ db_type | default("sqlite") }}'
    state: present
  when: db_type in multiflexi_server_database_engines
  tags: ['multiflexi']
