---

- name: Configure APT
  ansible.builtin.include_tasks:
    file: tasks/apt.yml

- name: Configure web server
  ansible.builtin.include_tasks:
    file: tasks/webserver.yml

- name: Configure database
  ansible.builtin.include_tasks:
    file: tasks/database.yml

- name: Configure PHP
  ansible.builtin.include_tasks:
    file: tasks/php.yml

- name: Install MultiFlexi multi package
  ansible.builtin.include_tasks:
    file: tasks/multiflexi.yml
