---
- name: Check PHP versions using phpquery -V
  ansible.builtin.command: /usr/sbin/phpquery -V
  register: phpversions
  changed_when: false
  failed_when: false
  ignore_errors: true

- name: Convert PHP versions list to dictionary
  ansible.builtin.set_fact:
    phpversions_dict: "{{ dict(phpversions.stdout_lines | map('regex_replace', '^(.*)$', '\\1') | list | zip(phpversions.stdout_lines)) }}"

- name: Enable mail.add_x_header in php.ini
  ansible.builtin.lineinfile:
    path: /etc/php/{{ item.key }}/cli/php.ini
    line: mail.add_x_header = On
    state: present
  with_dict: "{{ phpversions_dict }}"
  when: phpversions.stdout_lines is defined
  become: true
