---
- name: Find all installed app manifests
  ansible.builtin.find:
    paths: /usr/lib
    patterns: "*.app.json"
    recurse: true
  register: app_manifests

- name: Read app manifests
  ansible.builtin.slurp:
    src: "{{ item.path }}"
  loop: "{{ app_manifests.files }}"
  register: app_manifest_contents

- name: Create runtemplate for each installed app
  vitexus.multiflexi.runtemplate:
    state: present
    name: "demo_{{ (item.content | b64decode | from_json).name.en }}"
    app_uuid: "{{ (item.content | b64decode | from_json).uuid }}"
    company: "{{ demo_company_id | default('DEMO') }}"
  loop: "{{ app_manifest_contents.results }}"
  become: true
  register: runtemplate_results
