---
- name: Discover available MultiFlexi packages
  ansible.builtin.shell:
    cmd: apt-cache -q search multiflexi | awk '{print $1}'
  register: multiflexi_packages_discovered
  changed_when: false

- name: Apply package skiplist
  ansible.builtin.set_fact:
    multiflexi_packages_to_install: "{{ multiflexi_packages_discovered.stdout_lines | difference(demo_package_skiplist) | sort }}"

- name: Install all available MultiFlexi packages
  ansible.builtin.apt:
    name: "{{ multiflexi_packages_to_install }}"
    state: present
  become: true
  tags: ['demo', 'packages']

- name: Ensure all app manifests are imported
  ansible.builtin.command: multiflexi-json2apps
  become: true
  changed_when: false
  tags: ['demo', 'packages']
