---
- name: Ensure the MultiFlexi is installed
  multiflexi_info:
  register: multiflexi_info
- name: Show MultiFlexi information
  ansible.builtin.debug:
    var: multiflexi_info

- name: Include tasks from the demo role
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - create_company.yml
    - create_user.yml
    - create_app.yml
    - create_job.yml
    - manage_credential_type.yml
    - manage_topic.yml
  tags: demo_tasks
- name: Final message
  ansible.builtin.debug:
    msg: "Demo tasks completed successfully."
