---
- name: Create a job using MultiFlexi
  job:
    state: present
    app_id: "{{ app_id | default(omit) }}"
    runtemplate_id: "{{ runtemplate_id | default(omit) }}"
    scheduled: "{{ scheduled | default(omit) }}"
    executor: "{{ executor | default('native') }}"
  register: job_result

- name: Print job_result for debugging
  ansible.builtin.debug:
    var: job_result

- name: Assert that job creation was successful
  ansible.builtin.assert:
    that:
      - job_result.job is defined
      - job_result.job.id is defined
    fail_msg: "Failed to create or schedule job"
    success_msg: "Job created and scheduled successfully"

- name: Set fact with scheduled job info
  ansible.builtin.set_fact:
    scheduled_job_info: "{{ job_result.job }}"